import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { manrope } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "HTML+CSS Challenges - Register",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          manrope.className,
          "flex min-h-screen items-center justify-center bg-stone-100 text-gray-500 antialiased",
        )}
      >
        {children}
      </body>
    </html>
  );
}
